/*
 * port.h
 *
 * Created: 9/10/2024 3:55:52 AM
 *  Author: Mohamed Tarek
 */ 


#ifndef PORT_H_
#define PORT_H_

#include "../GPIO/gpio.h"
#define PIN_INPUT 0 
#define PIN_OUTPUT 1 

#define OUTPUT_LOW	0
#define OUTPUT_HIGH	0

#define PORTA_INIT_VAL_PIN0 OUTPUT_LOW
#define PORTA_INIT_VAL_PIN1 OUTPUT_LOW
#define PORTA_INIT_VAL_PIN2 OUTPUT_LOW
#define PORTA_INIT_VAL_PIN3 OUTPUT_LOW
#define PORTA_INIT_VAL_PIN4 OUTPUT_LOW
#define PORTA_INIT_VAL_PIN5 OUTPUT_LOW
#define PORTA_INIT_VAL_PIN6 OUTPUT_LOW
#define PORTA_INIT_VAL_PIN7 OUTPUT_LOW

#define PORTB_INIT_VAL_PIN0 OUTPUT_LOW
#define PORTB_INIT_VAL_PIN1 OUTPUT_LOW
#define PORTB_INIT_VAL_PIN2 OUTPUT_LOW
#define PORTB_INIT_VAL_PIN3 OUTPUT_LOW
#define PORTB_INIT_VAL_PIN4 OUTPUT_LOW
#define PORTB_INIT_VAL_PIN5 OUTPUT_LOW
#define PORTB_INIT_VAL_PIN6 OUTPUT_LOW
#define PORTB_INIT_VAL_PIN7 OUTPUT_LOW
 
 
 
#define PORTC_INIT_VAL_PIN0 OUTPUT_LOW
#define PORTC_INIT_VAL_PIN1 OUTPUT_LOW
#define PORTC_INIT_VAL_PIN2 OUTPUT_LOW
#define PORTC_INIT_VAL_PIN3 OUTPUT_LOW
#define PORTC_INIT_VAL_PIN4 OUTPUT_LOW
#define PORTC_INIT_VAL_PIN5 OUTPUT_LOW
#define PORTC_INIT_VAL_PIN6 OUTPUT_LOW
#define PORTC_INIT_VAL_PIN7 OUTPUT_LOW


#define PORTD_INIT_VAL_PIN0 OUTPUT_LOW
#define PORTD_INIT_VAL_PIN1 OUTPUT_LOW
#define PORTD_INIT_VAL_PIN2 OUTPUT_LOW
#define PORTD_INIT_VAL_PIN3 OUTPUT_LOW
#define PORTD_INIT_VAL_PIN4 OUTPUT_LOW
#define PORTD_INIT_VAL_PIN5 OUTPUT_LOW
#define PORTD_INIT_VAL_PIN6 OUTPUT_LOW
#define PORTD_INIT_VAL_PIN7 OUTPUT_LOW



#define PORTA_PIN0 PIN_OUTPUT
#define PORTA_PIN1 PIN_OUTPUT
#define PORTA_PIN2 PIN_OUTPUT
#define PORTA_PIN3 PIN_OUTPUT
#define PORTA_PIN4 PIN_OUTPUT
#define PORTA_PIN5 PIN_OUTPUT
#define PORTA_PIN6 PIN_OUTPUT
#define PORTA_PIN7 PIN_OUTPUT

#define PORTB_PIN0 PIN_OUTPUT
#define PORTB_PIN1 PIN_OUTPUT
#define PORTB_PIN2 PIN_OUTPUT
#define PORTB_PIN3 PIN_OUTPUT
#define PORTB_PIN4 PIN_OUTPUT
#define PORTB_PIN5 PIN_OUTPUT
#define PORTB_PIN6 PIN_OUTPUT
#define PORTB_PIN7 PIN_OUTPUT



#define PORTC_PIN0 PIN_OUTPUT
#define PORTC_PIN1 PIN_OUTPUT
#define PORTC_PIN2 PIN_OUTPUT
#define PORTC_PIN3 PIN_OUTPUT
#define PORTC_PIN4 PIN_OUTPUT
#define PORTC_PIN5 PIN_OUTPUT
#define PORTC_PIN6 PIN_OUTPUT
#define PORTC_PIN7 PIN_OUTPUT


#define PORTD_PIN0 PIN_OUTPUT
#define PORTD_PIN1 PIN_OUTPUT
#define PORTD_PIN2 PIN_OUTPUT
#define PORTD_PIN3 PIN_OUTPUT
#define PORTD_PIN4 PIN_OUTPUT
#define PORTD_PIN5 PIN_OUTPUT
#define PORTD_PIN6 PIN_OUTPUT
#define PORTD_PIN7 PIN_OUTPUT

#define CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0)		0b##b7##b6##b5##b4##b3##b2##b1##b0
#define CONC(b7,b6,b5,b4,b3,b2,b1,b0)	CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0)


#define PORTA_DIR(b7,b6,b5,b4,b3,b2,b1,b0)		CONC(b7,b6,b5,b4,b3,b2,b1,b0)
#define PORTB_DIR(b7,b6,b5,b4,b3,b2,b1,b0)		CONC(b7,b6,b5,b4,b3,b2,b1,b0)
#define PORTC_DIR(b7,b6,b5,b4,b3,b2,b1,b0)		CONC(b7,b6,b5,b4,b3,b2,b1,b0)
#define PORTD_DIR(b7,b6,b5,b4,b3,b2,b1,b0)		CONC(b7,b6,b5,b4,b3,b2,b1,b0)

#define PORTA_INIT_VALUE(b7,b6,b5,b4,b3,b2,b1,b0)		CONC(b7,b6,b5,b4,b3,b2,b1,b0)
#define PORTB_INIT_VALUE(b7,b6,b5,b4,b3,b2,b1,b0)		CONC(b7,b6,b5,b4,b3,b2,b1,b0)
#define PORTC_INIT_VALUE(b7,b6,b5,b4,b3,b2,b1,b0)		CONC(b7,b6,b5,b4,b3,b2,b1,b0)
#define PORTD_INIT_VALUE(b7,b6,b5,b4,b3,b2,b1,b0)		CONC(b7,b6,b5,b4,b3,b2,b1,b0)

Std_ReturnType PORT_INIT_FUN(void);




#endif /* PORT_H_ */