/*
 * port.c
 *
 * Created: 9/10/2024 4:29:34 AM
 *  Author: Mohamed Tarek
 */ 
#include "port.h"

Std_ReturnType PORT_INIT_FUN(void){
	
	DDRA_ = PORTA_DIR(PORTA_PIN7,PORTA_PIN6,PORTA_PIN5,PORTA_PIN4,PORTA_PIN3,PORTA_PIN2,PORTA_PIN1,PORTA_PIN0);
	DDRB_ = PORTB_DIR(PORTB_PIN7,PORTB_PIN6,PORTB_PIN5,PORTB_PIN4,PORTB_PIN3,PORTB_PIN2,PORTB_PIN1,PORTB_PIN0);
	DDRC_ = PORTC_DIR(PORTC_PIN7,PORTC_PIN6,PORTC_PIN5,PORTC_PIN4,PORTC_PIN3,PORTC_PIN2,PORTC_PIN1,PORTC_PIN0);
	DDRD_ = PORTD_DIR(PORTD_PIN7,PORTD_PIN6,PORTD_PIN5,PORTD_PIN4,PORTD_PIN3,PORTD_PIN2,PORTD_PIN1,PORTD_PIN0);
	
	PORTA_ = PORTA_INIT_VALUE(PORTA_INIT_VAL_PIN7,PORTA_INIT_VAL_PIN6,PORTA_INIT_VAL_PIN5,PORTA_INIT_VAL_PIN4,PORTA_INIT_VAL_PIN3,PORTA_INIT_VAL_PIN2,PORTA_INIT_VAL_PIN1,PORTA_INIT_VAL_PIN0);
	PORTB_ = PORTB_INIT_VALUE(PORTB_INIT_VAL_PIN7,PORTB_INIT_VAL_PIN6,PORTB_INIT_VAL_PIN5,PORTB_INIT_VAL_PIN4,PORTB_INIT_VAL_PIN3,PORTB_INIT_VAL_PIN2,PORTB_INIT_VAL_PIN1,PORTB_INIT_VAL_PIN0);
	PORTC_ = PORTC_INIT_VALUE(PORTC_INIT_VAL_PIN7,PORTC_INIT_VAL_PIN6,PORTC_INIT_VAL_PIN5,PORTC_INIT_VAL_PIN4,PORTC_INIT_VAL_PIN3,PORTC_INIT_VAL_PIN2,PORTC_INIT_VAL_PIN1,PORTC_INIT_VAL_PIN0);
	PORTD_ = PORTD_INIT_VALUE(PORTD_INIT_VAL_PIN7,PORTD_INIT_VAL_PIN6,PORTD_INIT_VAL_PIN5,PORTD_INIT_VAL_PIN4,PORTD_INIT_VAL_PIN3,PORTD_INIT_VAL_PIN2,PORTD_INIT_VAL_PIN1,PORTD_INIT_VAL_PIN0);
	
	
	
}